server:
  port: 17000

spring:
  application:
    name: m-pop-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin-api
          uri: lb://m-pop-admin
          predicates:
            - Path=/admin/**

        - id: product-api
          uri: lb://m-pop-product
          predicates:
            - Path=/product/**